#!/usr/bin/env python3
"""Generate docs/reference/curriculum.md and docs/explanation/gap-analysis.md from curriculum.py.

Both are derived from the manifest plus the live notebook status, so they never drift.
Run:  python generate_docs.py

Both outputs open with the `Status · Updated · Owner` banner the documentation standard
requires, stamped with the day they were generated — a generated index is current as of
the run that wrote it, and a generator that stripped the banner would quietly demote a
compliant document every time it ran. Both are written INTO docs/, under the directory
docs/README.md links them from; an output path that does not match the tracked file is
how the tracked file goes stale while a regenerated orphan sits beside it.
"""

from __future__ import annotations

from datetime import date

from curriculum import DOMAINS, NOTEBOOKS_DIR, ROOT, Domain
from nbstatus import BADGE, notebook_status


def _banner() -> str:
    return f"> **Status:** Current · **Updated:** {date.today():%Y-%m-%d} · **Owner:** praxis"


def _legacy_topics(domain: Domain):
    """(rel_path, title, status) for every notebook under a filesystem domain."""
    base = NOTEBOOKS_DIR / domain.dir
    out = []
    for p in sorted(base.rglob("*.ipynb")):
        rel = p.relative_to(base)
        status, _ = notebook_status(p)
        title = p.stem.replace("-", " ").title()
        out.append((rel.as_posix(), title, status))
    return out


def _status_counts() -> dict[str, int]:
    counts = {"scaffold": 0, "partial": 0, "complete": 0, "error": 0}
    for p in NOTEBOOKS_DIR.rglob("*.ipynb"):
        counts[notebook_status(p)[0]] = counts.get(notebook_status(p)[0], 0) + 1
    return counts


def gen_curriculum() -> str:
    total = sum(1 for _ in NOTEBOOKS_DIR.rglob("*.ipynb"))
    c = _status_counts()
    lines = [
        "# Curriculum",
        "",
        _banner(),
        "",
        "_Generated by `generate_docs.py` from `curriculum.py` — do not edit by hand._",
        "",
        f"**{total} notebooks** across **{len(DOMAINS)} domains** · "
        f"{BADGE['complete']} {c['complete']} complete · "
        f"{BADGE['partial']} {c['partial']} partial · "
        f"{BADGE['scaffold']} {c['scaffold']} scaffold",
        "",
        "Legend: ✅ complete · 🟡 partial · 🔴 scaffold · ⭐ recommended addition "
        "(not in the original study list).",
        "",
    ]
    for d in DOMAINS:
        lines.append(f"## {d.dir.split('-', 1)[1].replace('-', ' ').title()} — {d.title}")
        lines.append("")
        lines.append(d.blurb)
        lines.append("")
        if d.source == "filesystem":
            for rel, title, status in _legacy_topics(d):
                href = f"../../notebooks/{d.dir}/{rel}"
                lines.append(f"- {BADGE[status]} [{title}]({href})")
        else:
            for t in d.topics:
                status, _ = notebook_status(NOTEBOOKS_DIR / d.dir / f"{t.slug}.ipynb")
                star = " ⭐" if t.recommended else ""
                note = f" — _{t.note}_" if t.note else ""
                href = f"../../notebooks/{d.dir}/{t.slug}.ipynb"
                lines.append(f"- {BADGE[status]} [{t.title}]({href}){star}{note}")
        lines.append("")
    return "\n".join(lines)


def gen_gap_analysis() -> str:
    lines = [
        "# Gap Analysis",
        "",
        _banner(),
        "",
        "_Generated by `generate_docs.py`._ Coverage of the study list, suggested additions, "
        "and what already existed.",
        "",
        "## 1. Listed topics — coverage",
        "",
        "Every topic from the original study list now has a notebook (scaffold or filled). "
        "Status badges below; run `python -m praxis.construct` to fill the 🔴/🟡 ones "
        "to the [rubric](notebook-rubric.md).",
        "",
    ]
    for d in DOMAINS:
        if d.source != "manifest":
            continue
        listed = [t for t in d.topics if not t.recommended]
        if not listed:
            continue
        lines.append(f"### {d.title}")
        lines.append("")
        for t in listed:
            status, _ = notebook_status(NOTEBOOKS_DIR / d.dir / f"{t.slug}.ipynb")
            lines.append(f"- {BADGE[status]} {t.title}")
        lines.append("")

    lines += [
        "## 2. Recommended additions (not in the original list)",
        "",
        "High-value neighbors worth a refresher. They're already scaffolded and tagged "
        "`recommended` in `curriculum.py`, so the launcher and the constructor cover them too. "
        "Drop any "
        "you don't want by removing the topic from `curriculum.py`.",
        "",
    ]
    for d in DOMAINS:
        if d.source != "manifest":
            continue
        rec = [t for t in d.topics if t.recommended]
        if not rec:
            continue
        lines.append(f"### {d.title}")
        lines.append("")
        for t in rec:
            note = f" — {t.note}" if t.note else ""
            lines.append(f"- **{t.title}**{note}")
        lines.append("")

    lines += [
        "## 3. Existing but unlisted — the legacy library",
        "",
        "The repo already contained **64 MLOps / AWS / GPU-infra notebooks** on a different "
        "curriculum than the study list. Per the project decision they're retained as one domain, "
        "**DevOps/MLOps & Infra** (`notebooks/11-devops-mlops-infra/`), and their 34 template "
        "stubs are finished by the constructor alongside the new material.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    (ROOT / "docs" / "reference" / "curriculum.md").write_text(gen_curriculum() + "\n")
    (ROOT / "docs" / "explanation" / "gap-analysis.md").write_text(gen_gap_analysis() + "\n")
    print("wrote docs/reference/curriculum.md and docs/explanation/gap-analysis.md")


if __name__ == "__main__":
    main()
