#!/usr/bin/env bash
# check-roadmap-truth.sh — does ROADMAP.md still describe this repo?
#
# Three legs, each answering a way the roadmap and tasks/chief/ drift apart:
#
#   COVERAGE  every completed tasklist is named in the roadmap.       (merged work with no row)
#   STALE     no row marked OPEN names a tasklist that has MERGED.    (the row the work outgrew)
#   PARK      a parked tasklist reads as PARKED at every mention.     (a decision rendered as backlog)
#
# COVERAGE and PARK generalise an older single-repo guard. STALE is the leg the
# 2026-09-11 census asked for: 117 rows across 17 repos said ⬜/🚧 for work whose
# `completed/` record already carried a mergedToMain.
#
# This file is VENDORED into every repo that runs chief, public ones included, so it
# names no repository and carries no example a reader outside a given tree could not
# follow. The measurements behind its rules are stated as sizes and shapes, and that
# is deliberate rather than vague.
#
# It READS and never rewrites. Which row to add, and how to word it, is a judgement
# about what shipped — not a script's call.
#
# A TASKLIST IS CITED BY ITS FULL STEM. Nothing else counts — not `110`, not
# "tasklist 110", not | 110 |. This rule was arrived at the hard way on 2026-09-11:
# three rounds of number-matching produced three different wrong answers. Loose
# matching certified a `016-` stem as covered because a row elsewhere said
# "16 adopted dependencies"; tightening it to backticks and table cells then missed
# one repo's citation form entirely and doubled another's reported misses. A number
# is ambiguous in prose, and a gate that guesses is a gate that gets switched off.
# The full stem is unambiguous, greppable, and tells a reader WHICH work a row
# tracks — which is the property the roadmap wanted anyway. The repos that had
# spelled stems from the start are the ones this check never mis-read.
#
# A TABLE ROW'S STATUS IS ITS FIRST CELL. A real row seen in the fleet is 🚧 in its
# first cell while its last cell reads "closed by Phase A + `74-...`" — a row
# deliberately broader than the tasklist that merged. Judging the whole line would
# call that drift; judging the status cell calls it what it is.
#
# Portability: bash 3.2 (macOS /bin/bash) + awk. jq optional (PARK leg only).
#
# WHERE A STEM MAY BE NAMED. Two files, and the distinction is the point:
#
#   ROADMAP.md              — the PLAN. Prose and phase rows, written by a person.
#   docs/reference/tasklist-ledger.md — the RECORD. Every completed stem and its
#                             merge sha, GENERATED by scripts/roadmap-ledger.sh.
#
# Coverage is satisfied by either, because the two answer different questions and
# forcing the answer into one file wrecks it. The largest tree measured carries 406
# completed records against a 733-line roadmap: spelling all 406 there would bury
# the plan under its own history, and a roadmap nobody reads is the failure this
# check exists to stop.
# The ledger absorbs the bookkeeping; the roadmap keeps saying what is still true.
# The STALE leg reads ONLY the roadmap — a generated record has no opinion about
# what is open.
#
# Env overrides:  CHIEF_ROADMAP_FILE · CHIEF_TASKS_DIR · ROADMAP_TRUTH_ALLOW
#                 CHIEF_ROADMAP_LEDGER
# Exit 0 = pass or a loudly-reported skip; 1 = fail.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROADMAP="${CHIEF_ROADMAP_FILE:-$ROOT/ROADMAP.md}"
TASKS="${CHIEF_TASKS_DIR:-$ROOT/tasks/chief}"
LEDGER="${CHIEF_ROADMAP_LEDGER:-$ROOT/docs/reference/tasklist-ledger.md}"
DONE="$TASKS/completed"
ALLOW="${ROADMAP_TRUTH_ALLOW:-$ROOT/scripts/roadmap-truth-allow.txt}"

say()  { echo "roadmap: $*"; }
# Every leg runs and every failure prints. A gate that stops at the first failure
# makes a repo with three kinds of drift discover them one run at a time.
FAILED=0
fail() { echo "roadmap: FAIL — $*" >&2; FAILED=1; }
skip() {
  echo "roadmap: ┌──────────────────────────────────────────────────────────────"
  echo "roadmap: │ ROADMAP TRUTH CHECK SKIPPED — $1"
  echo "roadmap: │ This is NOT a pass. The roadmap may be arbitrarily far from what"
  echo "roadmap: │ this repo has shipped; this run could not measure it."
  echo "roadmap: └──────────────────────────────────────────────────────────────"
  [ "${GITHUB_ACTIONS:-}" = "true" ] && echo "::warning title=roadmap truth check skipped::$1"
  exit 0
}

[ -f "$ROADMAP" ] || skip "no roadmap at $ROADMAP"
[ -d "$DONE" ]    || skip "no $DONE — this tree records no completed tasklists"

JQ="$(command -v jq 2>/dev/null || true)"
TMP="$(mktemp -t roadmap-truth.XXXXXX)"; trap 'rm -f "$TMP" "$TMP.allow"' EXIT

# stems.tsv: stem \t merged(1|0).
#
# FIVE RECORD SHAPES, measured across the fleet 2026-09-11. Only the first two are
# MERGED; the STALE leg leaves every other row alone, because a row that stays open
# over work that was retired or handed upstream is not stale, it is accurate.
#
#   "mergedToMain": "<sha>"            MERGED — the ordinary case.
#   "mergedToMain": true               MERGED — an early record whose work is in the
#                                      tree without a recorded sha (6 such records in
#                                      one repo, and its roadmap says so). Reading
#                                      only sha-shaped values called these RETIRED,
#                                      which understated that repo's history by six.
#   "mergedToMain": "superseded@<sha>" RETIRED — the sha is where the supersession
#                                      landed, not where this tasklist merged.
#   no field + "supersededBy"          RETIRED by decision.
#   no field + "deliveredUpstream"     DELIVERED UPSTREAM — built in another repo.
#
# Anything else is UNKNOWN and is reported rather than bucketed: a record shape this
# check cannot read is exactly the thing that must not pass silently.
for f in "$DONE"/*.json; do
  [ -f "$f" ] || continue
  stem="$(basename "$f" .json)"
  if grep -qE '"mergedToMain"[[:space:]]*:[[:space:]]*("[0-9a-fA-F]{7,40}"|true)' "$f"; then
    printf '%s\t1\n' "$stem" >> "$TMP"
  elif grep -qE '"mergedToMain"|"supersededBy"|"deliveredUpstream"' "$f"; then
    printf '%s\t0\n' "$stem" >> "$TMP"
  else
    printf '%s\t0\n' "$stem" >> "$TMP"
    echo "roadmap: NOTE — $stem records neither a merge, a supersession nor an upstream delivery; treated as not-merged" >&2
  fi
done
[ -s "$TMP" ] || skip "$DONE holds no *.json — nothing to measure against"

: > "$TMP.allow"
[ -f "$ALLOW" ] && grep -v '^[[:space:]]*#' "$ALLOW" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' > "$TMP.allow"

SOURCES=("$ROADMAP")
[ -f "$LEDGER" ] && SOURCES+=("$LEDGER")

REPORT="$(awk -v stemfile="$TMP" -v allowfile="$TMP.allow" -v roadmapfile="$ROADMAP" '
BEGIN {
  FS = "\t"
  while ((getline l < stemfile) > 0) {
    split(l, a, "\t")
    N++; stem[N] = a[1]; merged[N] = (a[2] == "1"); seen[N] = 0
  }
  while ((getline l < allowfile) > 0) allow[l] = 1
  OPEN  = "⬜|🚧|🔴|⏸|\\(proposed\\)|proposed|planned|unrun|awaiting merge|on branch|not yet merged"
  DONEM = "✅|~~|merged|retired|shipped|complete|done|superseded"
  open_markers_present = 0
}
{
  line = $0
  # The ledger is a generated RECORD: it names stems for coverage and is never
  # read for status. Only the roadmap can be stale, because only the roadmap claims.
  is_roadmap = (FILENAME == roadmapfile)
  if (is_roadmap && line ~ OPEN) open_markers_present = 1
  # A markdown table row carries its status in the FIRST cell; anything else is
  # judged whole.
  cell = line
  if (substr(line, 1, 1) == "|") { split(line, c, "|"); cell = c[2] }
  # A ROW STATES ITS STATUS IN PROSE, NEVER IN ITS CITATIONS. Strip inline-code
  # spans before reading markers out of it. Stems are cited in backticks and
  # markers never are, and several real stems carry a done-word inside the slug
  # itself (`20-merged-in-tree`, `30-retired`, `50-superseded-at`). Judging the
  # raw text let the word "merged" INSIDE a citation cancel the ⬜ beside it, so
  # an open row over merged work read as done — the precise drift this leg exists
  # to catch, hidden by the name of the thing it was catching.
  status = cell
  gsub(/`[^`]*`/, "", status)
  row_open = is_roadmap && (status ~ OPEN) && (status !~ DONEM)
  for (i = 1; i <= N; i++) {
    if (index(line, stem[i]) == 0) continue
    seen[i] = 1
    if (row_open && merged[i] && !allow[stem[i]]) {
      s = line; if (length(s) > 150) s = substr(s, 1, 150) "…"
      stale = stale "    [" stem[i] "] " FNR ": " s "\n"
    }
  }
}
END {
  for (i = 1; i <= N; i++) {
    total++
    if (!seen[i]) missing = missing "  " stem[i] "\n"
    if (merged[i]) checked++
    if (allow[stem[i]]) exempt++
  }
  printf "TOTAL\t%d\nCHECKED\t%d\nEXEMPT\t%d\nOPENMARKERS\t%d\n", total, checked, exempt, open_markers_present
  printf "MISSING\n%sENDMISSING\n", missing
  printf "STALE\n%sENDSTALE\n", stale
}' "${SOURCES[@]}")"

sec() { printf '%s\n' "$REPORT" | awk -v a="$1" -v b="$2" '$0==a{f=1;next} $0==b{f=0} f'; }
val() { printf '%s\n' "$REPORT" | awk -v k="$1" -F'\t' '$1==k{print $2; exit}'; }

TOTAL="$(val TOTAL)"; CHECKED="$(val CHECKED)"; EXEMPT="$(val EXEMPT)"; HASOPEN="$(val OPENMARKERS)"
MISSING="$(sec MISSING ENDMISSING)"; STALE="$(sec STALE ENDSTALE)"

# ── COVERAGE ────────────────────────────────────────────────────────────────
if [ -n "$MISSING" ]; then
  fail "$(basename "$ROADMAP") does not name $(printf '%s\n' "$MISSING" | grep -c .) of the $TOTAL completed tasklists by full stem:
$MISSING
    Each is work that landed with no row naming it, so the file describes a repo
    that no longer exists. Cite the FULL stem in the row that tracks it — a bare
    number is not a citation, because prose is full of numbers. Bookkeeping that
    does not belong in the plan goes in the generated ledger instead:
        bash scripts/roadmap-ledger.sh --write
    Do NOT delete the record to make this pass."
else
  say "coverage OK — all $TOTAL completed tasklists are named in $(basename "$ROADMAP")$([ -f "$LEDGER" ] && echo " + $(basename "$LEDGER")")"
fi

# ── STALE ───────────────────────────────────────────────────────────────────
if [ "$HASOPEN" != "1" ]; then
  say "stale SKIPPED — this roadmap uses none of the open markers this check knows"
elif [ -n "$STALE" ]; then
  fail "$(basename "$ROADMAP") still shows work as OPEN that has merged:
$STALE
    Mark each row done (cite the merge sha), or — if the row is broader than the
    tasklist that merged — say in the row what REMAINS, so it stops claiming the
    whole thing is unstarted. A row that legitimately stays open while naming a
    merged stem goes in $(basename "$ALLOW") with a reason."
else
  say "stale OK — $CHECKED merged tasklist(s) checked, none shown as open$([ "${EXEMPT:-0}" -gt 0 ] && echo " ($EXEMPT allowlisted)")"
fi

# ── PARK ────────────────────────────────────────────────────────────────────
if [ -z "$JQ" ]; then
  say "park SKIPPED — jq not installed (the legs above ran)"
else
  PARKED=0
  for f in "$TASKS"/*.json; do
    [ -f "$f" ] || continue
    "$JQ" -e '.parked == true' "$f" >/dev/null 2>&1 || continue
    PARKED=$((PARKED + 1))
    stem="$(basename "$f" .json)"
    hits="$(grep -nF "$stem" "$ROADMAP")"
    [ -n "$hits" ] || fail "$stem declares \"parked\": true and the roadmap never names it.
    A park is a decision — here, $("$JQ" -r '.parkedReason // "see the record"' "$f" | head -c 120)…
    Recorded only where chief reads it, a person planning work cannot see it."
    bare="$(printf '%s\n' "$hits" | grep -vi 'park')"
    [ -n "$bare" ] && fail "$stem declares \"parked\": true, but the roadmap names it without saying so:
$(printf '%s\n' "$bare" | sed 's/^/    /' | cut -c1-140)
    Mark every mention PARKED (with the trigger it waits on), not ⬜ backlog."
    :
  done
  [ "$PARKED" -gt 0 ] && say "park OK — $PARKED parked tasklist(s) read as PARKED at every mention" \
                      || say "park OK — no tasklist declares \"parked\": true"
fi
exit "$FAILED"
