#!/usr/bin/env bash
# scripts/roadmap-ledger.sh — generate the record of what has merged.
#
# The companion to scripts/check-roadmap-truth.sh. That script asks whether every
# completed tasklist is named where a person can find it; this one writes the part
# of that answer no person should have to maintain by hand.
#
# WHY A SECOND FILE. ROADMAP.md is the PLAN — phase rows, prose, what is still
# true. The bookkeeping of "which stems merged, at which sha" is a RECORD, and in
# the repos with real history it is large: 406 records against a 733-line roadmap
# in one case, 219 against 545 in another. Spelling every stem in the roadmap
# would bury the plan under its own changelog. So the roadmap keeps the rows a
# person reasons about, and this ledger carries the full list.
#
# WHAT IT IS NOT. It is not evidence that anything WORKS. A record in completed/
# means a tasklist merged; whether the capability is real is a question for the
# roadmap's prose, and several repos carry rows that say "merged, and short of its
# deliverable" precisely because the two are different claims.
#
# The block between the markers is GENERATED — edits inside it are overwritten.
# Anything outside them is yours and is preserved.
#
# Usage:
#   bash scripts/roadmap-ledger.sh          # check: exit 1 if the block is stale
#   bash scripts/roadmap-ledger.sh --write  # regenerate in place
#
# Env: CHIEF_TASKS_DIR · CHIEF_ROADMAP_LEDGER
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TASKS="${CHIEF_TASKS_DIR:-$ROOT/tasks/chief}"
DONE="$TASKS/completed"
LEDGER="${CHIEF_ROADMAP_LEDGER:-$ROOT/docs/reference/tasklist-ledger.md}"
BEGIN='<!-- tasklist-ledger:begin -->'
END='<!-- tasklist-ledger:end -->'
WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1

[ -d "$DONE" ] || { echo "ledger: no $DONE — nothing to record"; exit 0; }

# Sort by numeric band then name, so the ledger reads in program order rather than
# in whatever order the filesystem hands them over.
TMP="$(mktemp -t roadmap-ledger.XXXXXX)"
trap 'rm -f "$TMP" "$TMP.body" "$TMP.new"' EXIT

# FIVE RECORD SHAPES, measured across the fleet 2026-09-11 — see the same table in
# scripts/check-roadmap-truth.sh, which must classify identically or the gate and the
# ledger will disagree about the same record.
#
#   "mergedToMain": "<sha>"            MERGED
#   "mergedToMain": true               MERGED, no sha recorded — the work is in the tree
#   "mergedToMain": "superseded@<sha>" RETIRED (that sha is the supersession)
#   no field + "supersededBy"          RETIRED by decision
#   no field + "deliveredUpstream"     DELIVERED UPSTREAM — built in another repo
#
# Anything else is UNKNOWN, and is written into the ledger as UNKNOWN rather than
# quietly counted as one of the four. A record this script cannot read is a fact
# about the record, and hiding it is how a ledger starts lying.
merged=0; retired=0; upstream=0; unknown=0; total=0

# A supersededBy value is free text that can carry `|`, which would break the table.
# Keep its first token — the stem it points at, which is the part that is a citation.
firstfield() { printf '%s' "${1%%[[:space:]]*}" | tr -d '|'; }

for f in "$DONE"/*.json; do
  [ -f "$f" ] || continue
  stem="$(basename "$f" .json)"
  num="${stem%%-*}"
  case "$num" in (*[!0-9]*|'') num=999999 ;; esac
  total=$((total + 1))
  sha="$(sed -n 's/.*"mergedToMain"[[:space:]]*:[[:space:]]*"\([0-9a-fA-F]\{7,40\}\)".*/\1/p' "$f" | head -1)"
  sup="$(sed -n 's/.*"supersededBy"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$f" | head -1)"
  if [ -n "$sha" ]; then
    merged=$((merged + 1))
    printf '%012d\t%s\t| `%s` | `%s` | merged |\n' "$num" "$stem" "$stem" "$sha" >> "$TMP"
  elif grep -qE '"mergedToMain"[[:space:]]*:[[:space:]]*true' "$f"; then
    merged=$((merged + 1))
    printf '%012d\t%s\t| `%s` | — | merged; no sha recorded, work is in the tree |\n' \
      "$num" "$stem" "$stem" >> "$TMP"
  elif [ -n "$sup" ] || grep -qE '"mergedToMain"[[:space:]]*:[[:space:]]*"superseded@' "$f"; then
    retired=$((retired + 1))
    printf '%012d\t%s\t| `%s` | — | retired by decision%s |\n' "$num" "$stem" "$stem" \
      "$([ -n "$sup" ] && echo ", superseded by \`$(firstfield "$sup")\`")" >> "$TMP"
  elif grep -qE '"deliveredUpstream"' "$f"; then
    upstream=$((upstream + 1))
    printf '%012d\t%s\t| `%s` | — | delivered upstream |\n' "$num" "$stem" "$stem" >> "$TMP"
  else
    unknown=$((unknown + 1))
    printf '%012d\t%s\t| `%s` | — | **UNKNOWN** — no merge, supersession or upstream record |\n' \
      "$num" "$stem" "$stem" >> "$TMP"
    echo "ledger: NOTE — $stem records no outcome this script can read" >&2
  fi
done

{
  printf '%s\n' "$BEGIN"
  printf '<!-- GENERATED by scripts/roadmap-ledger.sh — do not edit between these markers. -->\n\n'
  printf '_%s records — **%s** merged, **%s** retired by decision' "$total" "$merged" "$retired"
  [ "$upstream" -gt 0 ] && printf ', **%s** delivered upstream' "$upstream"
  [ "$unknown" -gt 0 ]  && printf ', **%s** UNKNOWN' "$unknown"
  printf '. Regenerate with `bash scripts/roadmap-ledger.sh --write`._\n\n'
  printf '| Tasklist | Merged to main | State |\n|---|---|---|\n'
  sort -k1,1 -k2,2 "$TMP" 2>/dev/null | cut -f3-
  printf '\n%s\n' "$END"
} > "$TMP.body"

if [ ! -f "$LEDGER" ]; then
  if [ "$WRITE" = 1 ]; then
    mkdir -p "$(dirname "$LEDGER")"
    {
      printf '# Tasklist ledger\n\n'
      printf '**Status:** Living · **Updated:** %s · **Owner:** the merge gate\n\n' "$(date +%Y-%m-%d)"
      printf 'Every tasklist this repo has completed, with the commit it merged as. This file is\n'
      printf 'the RECORD; [`ROADMAP.md`](../../ROADMAP.md) is the PLAN. A row here means a tasklist\n'
      printf 'merged — not that the capability behind it is finished, which is a claim only the\n'
      printf 'roadmap makes.\n\n'
      cat "$TMP.body"
    } > "$LEDGER"
    echo "ledger: created $LEDGER ($total records)"
    exit 0
  fi
  echo "ledger: FAIL — $LEDGER does not exist ($total completed records unrecorded)." >&2
  echo "        Create it with: bash scripts/roadmap-ledger.sh --write" >&2
  exit 1
fi

if ! grep -qF "$BEGIN" "$LEDGER"; then
  if [ "$WRITE" = 1 ]; then
    { cat "$LEDGER"; printf '\n'; cat "$TMP.body"; } > "$TMP.new" && mv "$TMP.new" "$LEDGER"
    echo "ledger: appended a generated block to $LEDGER ($total records)"
    exit 0
  fi
  echo "ledger: FAIL — $LEDGER has no '$BEGIN' marker." >&2
  echo "        Add one with: bash scripts/roadmap-ledger.sh --write" >&2
  exit 1
fi

awk -v b="$BEGIN" -v e="$END" -v body="$TMP.body" '
  index($0, b) { while ((getline l < body) > 0) print l; skip = 1; next }
  index($0, e) { skip = 0; next }
  !skip { print }
' "$LEDGER" > "$TMP.new"

if cmp -s "$LEDGER" "$TMP.new"; then
  echo "ledger: OK — $(basename "$LEDGER") records all $total completed tasklists ($merged merged, $retired retired)"
  exit 0
fi

if [ "$WRITE" = 1 ]; then
  mv "$TMP.new" "$LEDGER"
  echo "ledger: rewrote $(basename "$LEDGER") — $total records ($merged merged, $retired retired)"
  exit 0
fi

echo "ledger: FAIL — $(basename "$LEDGER") is out of date against $DONE." >&2
diff "$LEDGER" "$TMP.new" | head -20 | sed 's/^/        /' >&2
echo "        Regenerate with: bash scripts/roadmap-ledger.sh --write" >&2
exit 1
